columnsel = (
    'Name',
    'Farms',
    'Forestry, fishing, and related activities',
    'Oil and gas extraction','Mining, except oil and gas',         
    'Support activities for mining',
    'Utilities',
    'Construction',
    'Wood products',
    'Nonmetallic mineral products',
    'Primary metals',
    'Fabricated metal products',
    'Machinery',
    'Computer and electronic products',
    'Electrical equipment, appliances, and components',
    ' Motor vehicles, bodies and trailers, and parts',
    'Other transportation equipment',
    'Furniture and related products',
    'Miscellaneous manufacturing',
    'Food and beverage and tobacco products',
    'Textile mills and textile product mills',
    'Apparel and leather and allied products',
    'Paper products',
    'Printing and related support activities',
    'Petroleum and coal products',
    'Chemical products',
    'Plastics and rubber products',
    'Wholesale trade',
    'Motor vehicle and parts dealers',
    'Food and beverage stores',
    'General merchandise stores',
    'Other retail',
    'Air transportation',
    'Rail transportation',
    'Water transportation',
    'Truck transportation',
    'Transit and ground passenger transportation',
    'Pipeline transportation',
    'Other transportation and support activities',
    'Warehousing and storage',
    'Publishing industries, except internet (includes software)',
    'Motion picture and sound recording industries',
    'Broadcasting and telecommunications',
    'Data processing, internet publishing, and other information services',
    'Federal Reserve banks, credit intermediation, and related activities',
    'Securities, commodity contracts, and investments',
    'Insurance carriers and related activities',
    'Funds, trusts, and other financial vehicles',
    'Housing',
    'Other real estate',
    'Rental and leasing services and lessors of intangible assets',
    'Legal services',
    'Computer systems design and related services',
    'Miscellaneous professional, scientific, and technical services',
    'Management of companies and enterprises',
    'Administrative and support services',
    'Waste management and remediation services',
    'Educational services',
    'Ambulatory health care services',
    'Hospitals',
    'Nursing and residential care facilities',
    'Social assistance',
    'Performing arts, spectator sports, museums, and related activities',
    'Amusements, gambling, and recreation industries',
    'Accommodation',
    'Food services and drinking places',
    'Other services, except government',
    'Federal general government (defense)',
    'Federal general government (nondefense)',
    'Federal government enterprises',
    'State and local general government',
    'State and local government enterprises'
)